create table T_INVOICE_SEND_INVOICE
(
    OPERATOR      VARCHAR2(200),
    PROD_NO       VARCHAR2(20),
    PAYMENT       NUMBER,
    DISCOUNT      NUMBER,
    INVOICE_VALUE NUMBER,
    BILL_MONTH    VARCHAR2(20),
    STATUS        VARCHAR2(30),
    CURRENCY      VARCHAR2(10)
)
/

INSERT INTO T_INVOICE_SEND_INVOICE (OPERATOR, PROD_NO, PAYMENT, DISCOUNT, INVOICE_VALUE, BILL_MONTH, STATUS, CURRENCY) VALUES ('ORANGE', '88794058', 950580, 227920, 722660, '202009', 'UNPAID', 'USD');