create table T_INVOICE_CURRENCY
(
    CURRENCY VARCHAR2(60),
    AMOUNT   NUMBER
)
/

INSERT INTO T_INVOICE_CURRENCY (CURRENCY, AMOUNT) VALUES ('EUR', 3386.56);
INSERT INTO T_INVOICE_CURRENCY (CURRENCY, AMOUNT) VALUES ('USD', 2849.92);
INSERT INTO T_INVOICE_CURRENCY (CURRENCY, AMOUNT) VALUES ('SDR', 4048.71);